notifications:
  email:
    on_success: always

script: 'bundle exec rake spec'

rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.1
  - 1.9.2
  - 1.9.3-p125
  - 1.9.3-p194
  - 1.9.3-p286
  - 1.9.3-p327
  - 1.9.3-p362
  - 1.9.3-p374
  - 1.9.3-p385
  - 1.9.3
  - 1.9.3-head
  - 2.0.0-rc1
  - 2.0.0-rc2
  - 2.0.0

branches:
  only:
    - 'master'